### ISSUE TITLE
support for latest jellyfin nightly

### ISSUE THREAD

**Issue by Dnkhatri** [jellyfin/jellyfin-plugin-trakt#106]
With the latest nightly the plugin show notsupported

**Comment by crobibero** [comment]
Plugins are not built for unstable Jellyfin versions.

**Comment by Dnkhatri** [comment]
> Plugins are not built for unstable Jellyfin versions

@crobibero 
What would I need to do to build compatible versions. Is it just because of version mismatch or  actually something is broken. With github actions building the plugins looks easy so if it is just version mismatch I could just build them for myself after what ever need to be edited.

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-plugin-webhook/pull/106

This is the change that is required
