### ISSUE TITLE
Doesn't Actually Import Play States

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin-plugin-trakt#116]
Does not import actual play states like it does on emby and plex. all it imports is whether or not a movie/show has been played through 100%. if i were to watch a show half way through on plex or elsewhere and import play states, that would not reflect in jellyfin

**Comment by crobibero** [comment]
Duplicate of https://github.com/jellyfin/jellyfin-plugin-trakt/issues/32
