### ISSUE TITLE
Pick up an event after clicking mark as watched button

### ISSUE THREAD

**Issue by sambartik** [jellyfin/jellyfin-plugin-trakt#133]
After clicking "Mark as watched" button, the plugin does not pick that up and update trakt.tv accordingly. The current way to get around this is to run the "Export library to trakt.tv" task from the dashboard. It would be nice if that could be automatised right after marking, for example an entire season as watched.

**Comment by Shadowghost** [comment]
I'll take a look, I may have missed something.
