### ISSUE TITLE
Incorrect date of playback after manual export via Export to trakt.tv task

### ISSUE THREAD

**Issue by sambartik** [jellyfin/jellyfin-plugin-trakt#137]
When running the Export to trakt.tv task, if exporting a movie/episode that was not watched, but only marked as watched in jellyfin and at the same time there was no previous playback recorded of that movie/episode on trakt.tv, the watched date that gets exported is the current date, not the time at which point the media was marked as watched in the first place. Is this a bug or jellyfin does not retain date information for marked media?

**Comment by Shadowghost** [comment]
If the Jellyfin item has a `LastPlayedDate` set that information is used. If that isn't updated when a user marks something as watched we don't send any dates (I guess trakt will just use the current date?)
