### ISSUE TITLE
Regression: RetryEpisodeScrobble is broken

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-plugin-trakt#141]
Something changed after my PR #102  was deployed in v15. It was working fine and then stopped, possibly on the next version. I noticed the issue again when running v17. Rolled back to v15 and everything was working as expected. When v18 was deployed, it was broken again.

**Comment by SenorSmartyPants** [comment]
ATTN: @Shadowghost and @crobibero 

I think I found the cause of this breakage. RetryHttpRequest and response.EnsureSuccessStatusCode are checking HTTP status codes which is fine in theory, but this will catch 404 responses from scrobble, which is a valid response indicating that the episode or movie was not found. https://trakt.docs.apiary.io/#introduction/status-codes 

Since this exception is now caught and rethrown, execution never returns to SendEpisodeStatusUpdateAsync to try without episode ids.

**Comment by Shadowghost** [comment]
I'll check it tomorrow and come up with a PR. Thanks for investigating!

**Comment by SenorSmartyPants** [comment]
That PR looks good to me.
