### ISSUE TITLE
Duplicate Entry in Trakt

### ISSUE THREAD

**Issue by kooolarpan** [jellyfin/jellyfin-plugin-trakt#143]
Jellyfin-Server: 10.8.0
Trakt-Plugin: 18.0.0.0
Jellyfin-MPV-Shim: 2.0.2
Jellyfin Media Player: 1.7.0-pre4

Issue:
The plugin is acting weird as it tracked two plays of the same episode. The beginning and end of the episode are tracked as two plays.
![image](https://user-images.githubusercontent.com/33162706/168379712-dca419a2-9618-4d7c-af68-af5e28954944.png)
The above image shows the issue that I am facing right now.
![image](https://user-images.githubusercontent.com/33162706/168379739-6881e0ad-46cd-454a-a4ba-4d82be0dbd3c.png)
The log is of the above image, the entry time is of same as I quickly skipped to the end of the episode.

Logs:
https://pastebin.com/Hb1kfB8E

**Comment by Shadowghost** [comment]
There are exactly two stop events in your logs from two different sources. Can you enable debug logging and check again?

Does this only happen with MPV shim?

**Comment by kooolarpan** [comment]
I found out that with MPV Shim it records multiple time. With Media Player it is working fine.

**Comment by kooolarpan** [comment]
![image](https://user-images.githubusercontent.com/33162706/168484540-5bc2ca3b-a4e6-4b6d-bf8c-613e261715ba.png)

You can have a look at the logs.

**Comment by iwalton3** [comment]
This is probably caused by https://github.com/jellyfin/jellyfin-mpv-shim/blob/383540f4345c374ec5ea647569f7b6f1c4ac709f/jellyfin_mpv_shim/player.py#L623

**Comment by kooolarpan** [comment]
Ohh. Then it should be fixed.

**Comment by iwalton3** [comment]
Try this build if you're on Windows (or build from source against the latest master branch) https://github.com/jellyfin/jellyfin-mpv-shim/actions/runs/2328123477

**Comment by kooolarpan** [comment]
Installed it but got an error. 
![image](https://user-images.githubusercontent.com/33162706/168489445-e57dd534-673c-45fc-acee-27368467e62c.png)

**Comment by kooolarpan** [comment]
After installing new-build [https://github.com/jellyfin/jellyfin-mpv-shim/actions/runs/2329916590]. It is working fine
