### ISSUE TITLE
Plugin keeps marking the same specific episodes as watched even though the plays are fully deleted on Trakt.

### ISSUE THREAD

**Issue by zack317** [jellyfin/jellyfin-plugin-trakt#150]
Plugin keeps marking the same specific episodes as watched even though the plays are fully deleted on Trakt.

Every time jellyfin restarts or the Scheduled service to sync runs - it marks the same 5 episodes as played even though all Trakt history for such episodes have been deleted from Trakt. What exactly is it pulling it down from? 

It's really annoying because I do not want them to be marked as watched and have to constantly mark them as unwatched in Jellyfin and Trakt.

**Comment by d03j** [comment]
I have the exact same problem with two shows. try as I might, they get back to watched overnight. Ironically they don't seem to be marked as watched on trakt anymore...
