### ISSUE TITLE
"Export library to trakt.tv" task resets watched status of movies locally

### ISSUE THREAD

**Issue by blackwind** [jellyfin/jellyfin-plugin-trakt#151]
Here's a pretty straightforward one: Since upgrading to v10.8 and the latest Trakt plugin for v10.8, whenever the "Export library to trakt.tv" task is run, all movies (but NOT TV shows) are marked as unwatched locally. This can be resolved by running the "Import watch states and playback progress from trakt.tv" task -- these unwatched states aren't pushed to Trakt, so the correct data can easily be reimported -- but this is clearly not the intended behavior, so I'm submitting a bug report.

**Comment by Shadowghost** [comment]
We don't touch the local state when exporting the library. What other options do you have configured for your user?

**Comment by blackwind** [comment]
Set trakt.tv item to watched when local item is changed to watched, Set trakt.tv item to unwatched when local item is changed to unwatched, Synchronize collection, and Scrobble.

I can reproduce this every time I execute the task in question. Didn't occur in v10.7 with the same settings.

**Comment by Shadowghost** [comment]
Try reauthenticating the users please. We seem to ahve borked user data from the plugin shipped with 10.7.

**Comment by blackwind** [comment]
Tried, but the problem persists.

**Comment by blackwind** [comment]
I tried force re-authorization last time to no avail, and I've just gone in and de-authorized device entirely and removed Jellyfin from my Trakt account to start completely fresh. Same thing.

**Comment by Shadowghost** [comment]
Did you try deleting `/var/lib/jellyfin/plugins/configuration/Trakt.xml`, restarting Jellyfin and reauthing your user?

**Comment by blackwind** [comment]
Just tried it, no change.

**Comment by blackwind** [comment]
I thought it might have something to do with authorizing two Jellyfin users to the same Trakt account, but I just deleted my second Jellyfin user, stopped Jellyfin, deleted `Trakt.xml`, started Jellyfin, reauthorized, and the problem persists.

**Comment by blackwind** [comment]
Yep, you're right, Denis. Thanks for tracking that down!

Can we get a fix, @Shadowghost?
