### ISSUE TITLE
Purpose of "Export media info" is unclear

### ISSUE THREAD

**Issue by Avamander** [jellyfin/jellyfin-plugin-trakt#155]
It would be very nice if this configuration option had a bit more information about its use and impact.

**Comment by Shadowghost** [comment]
Not sure what there is more to say. It exports the media info of your files to Trakt and updates items on Trakt when those Infos change.

This info includes:
* resolution
* audio codec
* audio channels
* 3D or not
* HDR type
* media format (always digital)
