### ISSUE TITLE
Watching a show on Jellyfin reports multiple episodes to trakt at the same time

### ISSUE THREAD

**Issue by Appoxo** [jellyfin/jellyfin-plugin-trakt#158]
## Issue: 
- When I rewatched the show Overlord in anticipation of the 4th season I noticed that Trakt scrobbles multiple episodes at the same time and submits it to Trakt. This results in multiple rewatches of an episode (sometimes up to 2-5x) even for unreleased episodes.
- Sometimes if I interrupt playback (Just a usual "Nah I am not in the mood for this episode" reaction) the scrobbling to trakt still takes place

## What I do to recreate the issue:
- Open a show
- Open an episode and watch it
- Monitor Trakt via mobile browser (Shows the actual show in the scrobble banner and sometimes multiple others)
- Finish show and refresh Trakt history page
- Playback always with libVLC since NexoPlayer doesn't seem to like releases with SSA-Subs (so almost all anime releases)

## Troubleshoot steps taken so far:
- Changed the plugin version up to 17.0.0.0
- Reinstalled the plugin
- Deauthorized my account (2 at the moment of installation: My main account and an admin account)
- Purged Jellyfin install
- Reidentified the show
- Watched other shows -> Seems to impact two shows at the time of writing: One Piece and Overlord
- Watch some movies -> No problem with those (as far as I noticed)

A bit of a different issue: One Piece episodes are not scrobbled at all. Same library (Type: TV-show)

## **Environment:** 
How you installed Jellyfin (upgrade or fresh install)
-> Fresh

**What platform and operating system you're using (Debian, Arch, Docker, etc.)**
OS: 
-> x64, i5 11th gen, docker 5:20.10.17\~3-0\~debian-bullseye, docker-compose and Debian as underlying OS
-> Docker Image at the time: Linuxserver.io version:- 10.8.1-1-ls171 Build-date:- 2022-07-20T22:44:26-05:00
-> Linuxserver/jellyfin:latest

Jellyfin:
-> Server: Jellyfin, Version: 10.8.1,  Operating System: Linux
-> Plugin version: 19.0.0.0

**What you were doing that caused the issue to appear**
-> Watched an episode of a show that released yesterday

**Any relevant log output**
-> The truly relevant log output is always at the end but decided to create whole outputs in case it is needed. If you want more specific, please tell me
- Multiple wrong episodes to Trakt: https://pastebin.com/Ki2W9fhs
- After playing Overlord S4E4: https://pastebin.com/i1ffbMi1
- After playing One Piece S18E17: https://pastebin.com/ZgzadU9Q

**Any non-standard configurations you use**
-> I don't think so. Should be a standard config of an intel APU, docker and debian

**How am I consuming?**
-> Chromecast with Android TV (Beta android App (jellyfin-androidtv 0.14.0-beta.2 release)), Jellyfin Web (Chrome), Jellyfin Media Player Windows

## Some pictures describing my issue 
What happened during replay of episode 4 of Overlord:
![image](https://user-images.githubusercontent.com/17850993/181357749-c43792f9-43db-4d28-81b9-93f0bb7851ed.png)

After the episode stopped: _(the crossed out episode is the one I watched initially. So just ignore that one)_
![image](https://user-images.githubusercontent.com/17850993/181362020-34c0468f-046d-4cab-9e02-7d5dfabd551c.png)

My Trakt-plugin settings:
![image](https://user-images.githubusercontent.com/17850993/181363278-ad587ab1-e08c-4d59-8e71-60c0f0296693.png)

During playback of One Piece EP S18E16
![image](https://user-images.githubusercontent.com/17850993/181364340-3d69767e-6613-4b68-abc1-2faedcffbfec.png)

During playback it corrected itself and showed the correct show but with incorrect progress
![image](https://user-images.githubusercontent.com/17850993/181366588-8d824dde-5dae-467b-972c-00ca01023c76.png)
Update: Shortly after submitting, Trakt showed the following entries: (again the crossed out are the correct ones)
![image](https://user-images.githubusercontent.com/17850993/181372441-29d33fab-b908-4fa0-9312-c664c62f10c9.png)

**Comment by Appoxo** [comment]
I hope I didn't miss anything important out.

**Comment by Shadowghost** [comment]
Trakt heavily relies on IDs being present in your metadata. Do you use TMBD or TVDB for you metadata?

In the current iteration of the code there are not many places where multiple scrobbles can happen without it being marked multiple times within Jellyfin, did you try with only the trakt plugin installed?
We're using the Pause event when syncing state to Trakt, Stop (and therefore the "I'm done watching this" event) marks things as watched when 80% of the playtime is watched. That's why we only use it when Jellyfin says the playback has completed.
The Pause event sends a percentage to Trakt, which is calculated from the media metadata and the amount of ticks played from the playback tracker, if there's a bug I don't think it's in the plugin.

**Comment by Appoxo** [comment]
Regarding my metadata: I primarily use theTVDB ![Screenshot_2022-07-28-13-16-26-05_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/17850993/181493016-843977f3-f584-46eb-9515-522744322ca4.jpg)

I will try your fix later this evening. I will update this comment.

**Comment by Shadowghost** [comment]
That might be a problem because Trakt matches against TMDb and IMDb, while tvdb works in some cases but they deprecated it.

**Comment by Appoxo** [comment]
> That might be a problem because Trakt matches against TMDb and IMDb, While tvdb works in some cases, tvdb deprecated it and we fall back to matching series + episode number (which is unrealiable).

In that case I will try to use TMDb (is there even an IMDb plugin?) for anime and tv and will report back how it works out.

**Comment by crobibero** [comment]
> is there even an IMDb plugin?

IMDb doesn't have an api so there is no plugin

**Comment by Appoxo** [comment]
Okay new update: When I set everything up I noticed that something added 30 plays to each of the last 15 remaining episodes of a season. Let's see if the ideas can fix it:

> Can you try if #154 fixes your problem? If you've enabled exporting metadata there is a bug which may cause duplicate entries.

I removed the option (Export media info) in the plugin, restarted the container and rewatched Overwatch S4E4 (because Overwatch has a reliable hitrate on this issue): The playback is recognized immediately by trakt (according to the website). BUT it still shows several other episodes being scrobbled. In the end it "played back".
According to jellyfin my playback stopped at 22:27. 
According to trakt I had playback of S4E4 at 22:31 and a slow trickle of the following episodes (5-8) at the times: S4E5 22:35, S4E6 22:39, S4E7 22:43, S4E8 22:48 and again S4E4 at 22:56
After another restart I have the same issue again. Seems like this is not the solution are at least the only one and only a part... :(

PS: After the first restart I got hit again by the playback bomb with One Piece episodes on trakt.

> That might be a problem because Trakt matches against TMDb and IMDb, While tvdb works in some cases, tvdb deprecated it and we fall back to matching series + episode number (which is unrealiable).

So far I uninstalled a number of not used plugins and disabled theTVDB for good measure as well. (If trakt deems it unnecessary I don't really need it right now) and now have those plugins enabled: 
![image](https://user-images.githubusercontent.com/17850993/181827036-84b72157-c03b-4d7e-9758-0d43cb444b7c.png)
and Overlord is identified as this:
![image](https://user-images.githubusercontent.com/17850993/181827480-66cba609-899d-4f2f-8dcc-ba3c84058171.png)

I refreshed the whole library yesterday (without removing pictures) and have watched overlord S4E4. Unfortunately as soon as I hit F5 to refresh the trakt page I saw multiple scrobbles to trakt up to E13 :(
The log after I hit play: https://pastebin.com/zNByjzT7

**Comment by Shadowghost** [comment]
Might be caused by your naming scheme: `Overlord (2015) - S04E04 - E043` could be interpreted as `S04E04-E043` which would then be most likely messed up by the parser into multiple plays.

**Comment by Appoxo** [comment]
> Might be caused by your naming scheme: `Overlord (2015) - S04E04 - E043` could be interpreted as `S04E04-E043` which would then be most likely messed up by the parser into multiple plays.

Just to confirm: You think my current naming scheme makes the plugin and/or trakt interpret watching episode 04 (total episode number E43) think I am watching episode 04 up to 43?

Could make sense...I use the anime numbering of sonarr. As the anime naming scheme I use the one from trash guides ([here](https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/#anime-episode-format)).
It would also explain why One Piece is messed up, but regular tv shows like Mr.Bean scrobble just fine.
Afaik when I got a show that was combined beforehand (Halo 4 - Forward unto dawn) it is registered as S01E01-05
![image](https://user-images.githubusercontent.com/17850993/181830306-537ceb9f-126e-4583-9d0a-77e86b25a3e6.png)

I will try the tv naming scheme from trash guides and report back if it works!

**Comment by Appoxo** [comment]
Renaming the episodes does absolutely nothing. It seems like the metadata is my problem.
Some shows get absolute numbering (example: S2E2 - E22) and some get regular numbering as a title. I can't make out what decides to do what.
My metadata is set up like this:
![image](https://user-images.githubusercontent.com/17850993/181835347-218e23e9-78a7-4042-8285-ae60baa7688e.png)
Any recommendation on what to change?

**Comment by Appoxo** [comment]
Well...I think I found the source of this problem: Absolute numbering seems to be the culprit so you assumption was correct.
Could a a filter maybe help if jellyfin reports the episode as "S02E02 - 99"?
So far I watched 2 episodes of One Piece without any trouble and was even able to import a new show (with country as "Japan") without absolute numbering.
Should I raise an issue/suggestion on the main Jellyfin page about TV libraries option to enable/disable absolute numbering regardless of source whenever possible?

**Comment by Shadowghost** [comment]
Main problem should not be the absolute numbering but the absolute numbering and multiple episodes together. absolut enumbering with proper TMDB ids per episode would still work since we match on those ids before relying on episode and season numbers.
There isn't much we can do in this specific case imo.

**Comment by Appoxo** [comment]
> Main problem should not be the absolute numbering but the absolute numbering and multiple episodes together. Absolute numbering with proper TMDB ids per episode would still work since we match on those ids before relying on episode and season numbers.
> There isn't much we can do in this specific case imo.

Am i interpreting this correctly? I have to care that each episode is properly identified when mixing absolute and episode number or have only one of the systems running at once?

**Comment by Shadowghost** [comment]
Let me explain: The plugin does this when you watch an item:
* Check if the item has an tmdb or imdb id associated with it and is not a multi episode item
  * Post watched state with the id as identifier (this works even with absolute ordering since the episode number is irrelevant)
* If item has multiple episode numbers, those are used for scrobbling - this obviously fails if you're using absolute ordering while trakt uses aired ordering

**Comment by Appoxo** [comment]
Update since I actually watched some episodes of the troublemakers:
- Some episodes get scrobbled immediately while some others get a delayed scrobble
- *NO* multi-scrobbles -> Probably fixing the numbering was the culprit
- The scrobbling even accounts for pauses/stops as intended.

At this point I would probably close the ticket if you have no further questions
