### ISSUE TITLE
Duplicate plays bug auto remove

### ISSUE THREAD

**Issue by Dnkhatri** [jellyfin/jellyfin-plugin-trakt#162]
Every once in a while trakt add many views of the same episode or movie. Even the time is the same. So far I am using a python plugin to clean up duplicate plays but was wondering if the duplicate check can be added to the jellyfin plugin itself. If a episode is shown to be palyed 20-30 times at nine a clock then the plugin should remove those plays and keep 1 only.
Another request though that is not because of trakt bug I do not want a 2nd play of show or movie to be registered only the first play so removing all other plays after the first and not adding new plays if a movie is already shown as watched. This of course can be optional setting for users as some people might want to keep the data but for me only the first time I watched a movie is important not the repeat views so would prefer those plays not to be added.

**Comment by Shadowghost** [comment]
AFAIK this only happens if the playcount within Jellyfin is higher than the one in trakt. The plugin will then add the amount of plays at the most recent plays to match the playcount. Since Jellyfin only keeps the date and time of the most recent play we can't add the other plays at different dates.

This currently is intended behaviour but it could be argued that we should just not sync the playcount.

**Comment by GBMiro** [comment]
I'm having this duplicate issue right now with one show.
Would modifying the playcount on library.db for these episodes solve this issue?
I've seen that for each play, it creates 3 entries in the UserDatas table. Do I need to modify all of them?

**Comment by Dnkhatri** [comment]
> I'm having this duplicate issue right now with one show. Would modifying the playcount on library.db for these episodes solve this issue? I've seen that for each play, it creates 3 entries in the UserDatas table. Do I need to modify all of them?

do you want to remove duplicate from trakt or jellyfin. For trakt I am using this script 
https://github.com/anthonyfoulfoin/trakt-tv-duplicates-removal or you can also use this website
https://huere.net/trakt/duplicate_removal/

**Comment by GBMiro** [comment]
Both, actually.

Thanks for the script. I'll use it when it happens again.

The weird thing is that even after deleting all playcount for the episodes in jellyfin and trakt plays (resetting series progress), after executing the import task jellyfin will mark 6 episodes as watched, as though trakt had some views that I cannot see.
In this state, jellyfin won't import new views from trakt if I mark other episodes of the same show.

When I get everything working (same watched episodes in trakt & jellyfin), the task sends duplicate views to trakt with the current date for all episodes except those 6 I mentioned before.

**Comment by Jerrk** [comment]
https://github.com/jellyfin/jellyfin-plugin-trakt/issues/162#issuecomment-1235489057 i agree with this whole-heartedly. at the very least add another option for "sync playcount on most recent play" or something along those lines.
