### ISSUE TITLE
An error occurred when trying to authorize device: 500 - Internal Server Error

### ISSUE THREAD

**Issue by listy-bit** [jellyfin/jellyfin-plugin-trakt#176]
plugin 20.0.0.0
JF 10.8.4
Ubuntu 22.04

No scrobbles since yesterday morning.

**Comment by Shadowghost** [comment]
Please check our announcements on reddit and Matrix. Due to the plugin spamming the API our API key got disabled (see #174).

#175 should take care of the problem and after that PR is in we need to publish a new plugin version and you need to upgrade to it since the API key changed.
