### ISSUE TITLE
can't modify exclusion folders

### ISSUE THREAD

**Issue by ToXinE** [jellyfin/jellyfin-plugin-trakt#18]
![Image of trakt 4.0.0.0 problem](https://i.imgur.com/qHxU6Uu.gif)

as you can see, i cannot deselect folder exclusions.

I'm running jellyfin 1.3.2 on docker and trakt 4.0.0.0 plugin

**Comment by cvium** [comment]
Try a page refresh

**Comment by ToXinE** [comment]
already done on Firefox latest version. I tried ctrl+f5 too

**Comment by ToXinE** [comment]
not solved yet

**Comment by oddstr13** [comment]
@ToXinE Is this exact issue still present in Jellyfin v10.6.0 with jellyfin-plugin-trakt v10?

**Comment by ToXinE** [comment]
yes,
It seems the first checkbox is always checked back :(

**Comment by crobibero** [comment]
I can't replicate this locally, do you have any errors in your JS console or server log?

**Comment by ToXinE** [comment]
no error in js except when uncheking first entry : 'inputmanager : try to process blablabla...'
![image](https://user-images.githubusercontent.com/6205053/88443166-876f2800-ce17-11ea-9b92-16c972642cd4.png)

no logs at all in server logs :(

**Comment by Shadowghost** [comment]
Can't replicate this on the current version.
