### ISSUE TITLE
V21 not available

### ISSUE THREAD

**Issue by flonou** [jellyfin/jellyfin-plugin-trakt#183]
V21 has been out for many days now, but jellyfin still only sees v19 which is broken

**Comment by Shadowghost** [comment]
Are you on the latest Jellyfin version?

**Comment by flonou** [comment]
I'm on 10.8.1 that was the lastest a few days ago if I'm not mistaken

**Comment by crobibero** [comment]
10.8.1 was released on Jun 26, 2022
10.8.5 was released on Sep 24, 2022

**Comment by flonou** [comment]
Oh that's totally my bad then ! sorry !
