### ISSUE TITLE
Cannot update Trakt to 21.0

### ISSUE THREAD

**Issue by DemirG** [jellyfin/jellyfin-plugin-trakt#185]
Hi,

A couple of days ago when there was a problem with the plugin hammering the API I tried solving the problem by reinstalling Trakt Plugin. Reinstalled and removed all the Trakt files in JF server manually. Since then I saw that it was a plugin problem and should've not done anything. 

But my problem now is that I'm stuck on version 20.0. I can install it and all the releases before, but cannot install update 21.0. And on 20.0 I cannot connect to Trakt, getting error "An error occurred when trying to authorize device: 500 - Internal Server Error". 

I have the offical repo and tried adding another repo with the latest plugin version, but it still just gives me the 20.0 version to download.

**Comment by Shadowghost** [comment]
Make sure you're on the latest Jellyfin version. You'll also need to restart Jellyfin after updating the plugin.

**Comment by DemirG** [comment]
@Shadowghost seems to work now. You were right my JF server wasn't fully updated. I was still on 10.8.4. 
Works fine now. Will close the ticket.
