### ISSUE TITLE
"Authorize device" button not working 

### ISSUE THREAD

**Issue by shivindera** [jellyfin/jellyfin-plugin-trakt#194]
Nothing happens when I click on the Authorize button. I have tried it on different devices with same result.

In the browser console I see `Requesting url without automatic networking: http://192.168.178.233:8096/Trakt/Users/_USER_ID_/Authorize`.

**Comment by crobibero** [comment]
From https://status.trakt.tv/

> Website Back Online
> The Trakt website and Plex scrobbler are back online! We'll be closely monitoring the servers and database while things re-cache and ramp up. Trakt API will be turned on next week. Please read the dashboard (https://trakt.tv/dashboard) notice when signed into the website.
> December 16, 2022, 12:10 GMT+00:00

**Comment by shivindera** [comment]
Thanks!
