### ISSUE TITLE
Update Client ID for Jellyfin

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-plugin-trakt#2]
I will need to contact Trakt.tv to have this generated for us.

**Comment by cvium** [comment]
> I will need to contact Trakt.tv to have this generated for us.

It's automatic iirc?

**Comment by anthonylavado** [comment]
So I have a new Client ID and Client Secret, but based on the way this plug in is currently written, I probably shouldn’t release those just yet.

We should look into adapting this to use the Device authentication flow.

**Comment by anthonylavado** [comment]
Client ID: `58f2251f1c9e7275e94fef723a8604e6848bbf86a0d97dda82382a6c3231608c`
Client Secret: `bf9fce37cf45c1de91da009e7ac6fca905a35d7a718bf65a52f92199073a2503`

**Comment by anthonylavado** [comment]
I guess we can close this now?

**Comment by cvium** [comment]
Should probably wait for #5 to be merged
