### ISSUE TITLE
Sends duplicate data, exhausting trakt.tv API limits 

### ISSUE THREAD

**Issue by eldridgea** [jellyfin/jellyfin-plugin-trakt#216]
My trakt.tv access was blocked due to the Jellyfin plugin sending more than 200K play history items (for context my library only has several hundred items in it). 

When I disabled it and asked trakt.tv to reenabled my access I asked for clarity and got the info that they. "almost always see duplicate pushes of the same data on the same date." 

Is there a way to not push watched status for videos that have already been marked?

**Comment by Shadowghost** [comment]
That's exactly what we are doing. We compare the current watched status from Trakt to the local database and only post the diff. Without additional information there isn't much we can do.

**Comment by eldridgea** [comment]
OK, I'll chalk that up to me making a mistake or something then. 
Thank you!
