### ISSUE TITLE
Jellyfin marking series episodes 2x

### ISSUE THREAD

**Issue by JensDeLeersnyderPXL** [jellyfin/jellyfin-plugin-trakt#219]
When I finish a series episode jellyfin marks the episode 2x. These two plays in Trakt are marked as watched at the same time. 

Is this issue a misconfiguration on my end or is this an issue with the plugin?

**Comment by mortiis** [comment]
I experience this issue as well, but sometimes with 500+ plays on the same datetime. I've been in contact with Trakt support which had this to say: 

> ... all the of the plays were added by Jellyfin. This likely means they are re-sending the plays due to a metadata mismatch on their side. It should all work with Jellyfin matching Trakt based on IDs (TMDB, TVDB, etc) but I'm not familiar with how they have it coded. Jellyfin is incorrectly thinking those episodes aren't marked watched on Trakt, so it keeps re-syncing them. It would require a fix in the Jellyfin plugin since they are the developer of that plugin.

**Comment by JRDevo** [comment]
![Screenshot 2023-11-17 180039](https://github.com/jellyfin/jellyfin-plugin-trakt/assets/42043842/e1011fb7-8436-4a4b-8ce5-2391934c92d9)

I get this more than twice. Its so random, cant tell why it happens.

**Comment by JensDeLeersnyderPXL** [comment]
This issue is still present when you use the Jellyfin mobile app on android.

**Comment by WybeBosch** [comment]
This is still an issue, i have been in contact with support and after checking the logs they concluded its Jellyfin trakt plugin aswell. 
i did not watch the entire show bleach 3000 times :D 

![image](https://github.com/jellyfin/jellyfin-plugin-trakt/assets/40889930/6fa7e948-3d32-4219-9c25-53e9ee16fa53)

Debug from trakt side showing the amount of episodes being added each day.
![image](https://github.com/jellyfin/jellyfin-plugin-trakt/assets/40889930/a24f7da1-eedb-4f3a-950d-d9d165b93a36)
