### ISSUE TITLE
Can't sync to trakt anymore

### ISSUE THREAD

**Issue by gerrit507** [jellyfin/jellyfin-plugin-trakt#22]
After the update to 10.3.6 and the respective trakt plugin upgrade syncing from trakt to jellyfin works again. Syncing from jellyfin to trakt still doesn't work. It definitely worked until 10.3.6. It also seems unclear to me what the following option actually does:

Update Trakt watched history during Scheduled Task
If checked, Jellyfin will only sync from Trakt during the Trakt scheduled tasks. 

From the first sentence i get the impression that I have to tick it to sync to trakt but the second sentence basically tells the opposite. Anyways I tried both ticked and unticked with a restart in between and didn't work.

**Comment by anthonylavado** [comment]
Hey there! So the sync from Jellyfin to Trakt should happen automatically, once a certain amount of the media has been viewed.

There is also a regular check to pull from Trakt to Jellyfin, that happens automatically. The checkbox you described is if people *only* want that import to happen whenever the schedule task runs (like in the middle of the night, for example). So it should be syncing to Trakt no matter what right now.

What happens if you try to force re-authorize?

**Comment by anthonylavado** [comment]
My bad, I just remembered. This is all covered by #20, which is fixed by jellyfin/jellyfin#1522.

**Comment by gerrit507** [comment]
This means if jellyfin/jellyfin#1522 is merged, syncing from jellyfin to trakt should work again? Or is it supposed to work already?

**Comment by b0mb** [comment]
> This means if [jellyfin/jellyfin#1522](https://github.com/jellyfin/jellyfin/pull/1522) is merged, syncing from jellyfin to trakt should work again? Or is it supposed to work already?

at the moment u can´t even authorize a new account with the plugin - it needs to get fixed....

**Comment by joshuaboniface** [comment]
@b0mb Does the latest version of the plugin with 10.3.6 not work properly?

**Comment by b0mb** [comment]
Nah... It doesn't work 😐

Joshua M. Boniface <notifications@github.com> schrieb am Sa., 13. Juli
2019, 22:44:

**Comment by joshuaboniface** [comment]
OK, if you're on Debian can you try these `.deb`s with the v5 plugin and let me know? @oddstr13 confirmed it should fix it but more confirmation is better!

Debian deb: https://repo.jellyfin.org/releases/server/debian/versions/10.3.7b1/jellyfin_10.3.7-1_amd64.deb
Ubuntu deb: https://repo.jellyfin.org/releases/server/ubuntu/versions/10.3.7b1/jellyfin_10.3.7-1_amd64.deb

**Comment by joshuaboniface** [comment]
> OK, if you're on Debian can you try these `.deb`s with the v5 plugin and let me know? @oddstr13 confirmed it should fix it but more confirmation is better!
> 
> Debian deb: https://repo.jellyfin.org/releases/server/debian/versions/10.3.7b1/jellyfin_10.3.7-1_amd64.deb
> Ubuntu deb: https://repo.jellyfin.org/releases/server/ubuntu/versions/10.3.7b1/jellyfin_10.3.7-1_amd64.deb

Forgot to ping: @b0mb

**Comment by b0mb** [comment]
Hi!

Thx for support but I can try on Windows and docker. I use the docker
container on my unraid server. 😉

Joshua M. Boniface <notifications@github.com> schrieb am So., 14. Juli
2019, 01:13:

**Comment by gerrit507** [comment]
@joshuaboniface I'm also on docker. Hence unfortunately I can't test the .deb files.

**Comment by Rijul-A** [comment]
I have tried the Debian *.deb file and I get the following error now:
`[2019-07-24 21:20:56.057 +05:30] [INF] Executing "Sync library to trakt.tv"
[2019-07-24 21:20:56.109 +05:30] [ERR] Error
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at Trakt.Api.TraktApi.SetRequestHeaders(HttpRequestOptions options, TraktUser traktUser)
   at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2019-07-24 21:20:56.118 +05:30] [INF] "Sync library to trakt.tv" Failed after 0 minute(s) and 0 seconds`

However, the this does fix #20. Meanwhile let me know in case I can help with this further.

**Comment by oddstr13** [comment]
`10.3.7` is released and should have fixed this issue.

@Rijul-A could you test and see if this also solves your problem?

**Comment by gerrit507** [comment]
The trakt plugin is working again with 10.3.7. Thank you!

**Comment by Rijul-A** [comment]
@oddstr13 Thanks, the update from the official repo fixed it!
