### ISSUE TITLE
"An error occurred when trying to authorize device: 500 - Internal Server Error"

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [jellyfin/jellyfin-plugin-trakt#24]
https://b.catgirlsare.sexy/Tvcj.png

Am getting an error upon first install, when I click "Authorize Device" (So I can link to my Trakt account), an error pops up stating: "An error occurred when trying to authorize device: 500 - Internal Server Error".
Already tried a server restart."

Win10, Jellyfin 10.3.6

**Comment by Bond-009** [comment]
Please try with 10.3.7

**Comment by Z3ROGRAV1TYx** [comment]
My bad, that fixed it! Thank you!

**Comment by rushfly** [comment]
jellyfin 10.5.0 and Trakt 7.0.0.0 have same issue.
```An error occurred when trying to authorize device: 500```
