### ISSUE TITLE
Sync library to trakt.tv (failed)

### ISSUE THREAD

**Issue by karthistark** [jellyfin/jellyfin-plugin-trakt#29]
I installed jellyfin 10.4.0 version in windows. 
I have problem with sync library... Watched status.

**Comment by theg00s3** [comment]
I have the same issue

**Comment by xrishox** [comment]
is this an issue with syncing from trakt to jellyfin, to jellyfin from trakt or both?

i'm currently on 10.4.3 and trying to sync from trakt to jellyfin and it isn't working. I haven't tried syncing from jellyfin to trakt yet.

**Comment by anthonylavado** [comment]
Hi all, this should be working now in more recent updates. Please re-open if you're still having issues.
