### ISSUE TITLE
Trakt fails to load users in Jellyfin 10.4.0

### ISSUE THREAD

**Issue by jaredallard** [jellyfin/jellyfin-plugin-trakt#30]
Users won't load when launching trakt for the first time in a fresh 10.4.0 Jellyfin installation.

I assume this is somewhat related to #29 

<img width="837" alt="Screen Shot 2019-10-09 at 08 58 53" src="https://user-images.githubusercontent.com/2391349/66498502-09ea4f00-ea73-11e9-832f-1b8f0ecb6681.png">

### Details

**Jellyfin**: 10.4.0
**Trakt Plugin**: 7.0.0.0

**Comment by jaredallard** [comment]
Any ideas @joshuaboniface?

**Comment by anthonylavado** [comment]
@jaredallard Sorry for the delay on this. We think it’s related to this: https://github.com/jellyfin/jellyfin/pull/2008

**Comment by anthonylavado** [comment]
Hi @jaredallard,
Apologies for not following up on this. Everything seems to be fine in 10.4.3. Please re-open if you're still having issues.

**Comment by paolobasso99** [comment]
Hi,
I have the same issue in Jellyfin 10.5.5 with Trakt Plugin 9.0.0.0.
The select is empty:
`<select is="emby-select" id="selectUser" name="selectUser" onchange="if (!window.__cfRLUnblockHandlers) return false; TraktConfigurationPage.loadConfiguration(this.value);" label="Configure Trakt for:" data-cf-modified-fc2d8ecf3b52aedbfa284bb0-="" class="emby-select-withcolor emby-select"></select>`
![Annotation 2020-07-16 191056](https://user-images.githubusercontent.com/12545838/87701529-6d3ea580-c798-11ea-873a-196146afd3d4.jpg)
I am using the linuxserver docker image if it is relevant.

**Comment by oddstr13** [comment]
The user list is populated for me on unstable.
If it is indeed broken in 10.5.5, it'll most likely work in 10.6

**Comment by paolobasso99** [comment]
Just updated to 10.6 and now the plugin works!
