### ISSUE TITLE
Resume Time Import

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-plugin-trakt#32]
According to a user on Chat, the Trakt plug-in/Jellyfin appears to export current play progress,  but does not import it.

Consider this scenario:
* There is a media library, imported to Plex and Jellyfin
* Both servers are connected to Trakt

1) Watch movie to 50% in Jellyfin, synchronize to Trakt. Upon starting playback in Plex, you will resume at 50%.

2) Watch movie to 50% in Plex. Synchronize with Trakt. Upon launching in Jellyfin, it will start at the beginning.

The user would like Jellyfin to resume just as Plex does.

**Comment by giejay** [comment]
I thought I missed a checkbox when migrating from Emby to Jellyfin and not having my resume positions synced... But this is a not implemented feature I guess?

**Comment by anthonylavado** [comment]
@giejay That's right, it's not implemented yet. This is planned for the future.

**Comment by dannymichel** [comment]
Yes, this was me that reported this.

**Comment by dedors** [comment]
Because I switch between Kodi and Jellyfin, this would be much appreciated.

**Comment by foux** [comment]
Any news on this issue?

**Comment by dannymichel** [comment]
Other bugs were fixed with the release of 16, but this one doesn't seem to have been fixed. I wasn't aware this one was supposed to have even been addressed in the new release. Thought it was a ``future feature request``

**Comment by dannymichel** [comment]
might this have to do with a very recent change to trakt? https://github.com/trakt/api-help/discussions/341
that guy's app stopped working

**Comment by Shadowghost** [comment]
For whatever reason it takes quite a long time on Trakt to sync the pushed paused state with the results from the generic playback endpoint when you don't specify date borders (you can define a range of dates to check for paused playback).

On my tests the API instantly returned the paused playback when calling the endpoint with a date range but without it took several minutes (sometimes more than 10...) to appear.

I didn't have two clients to check if this feature works as intended but it should work in theory if the API provides the correct info.

Also keep in mind that playback progress is only synced from Trakt via the import task and is dropped if the local last watched date is newer than the paused date of the playback.

**Comment by dannymichel** [comment]
> For whatever reason it takes quite a long time on Trakt to sync the pushed paused state with the results from the generic playback endpoint when you don't specify date borders (you can define a range of dates to check for paused playback).
> 
> On my tests the API instantly returned the paused playback when calling the endpoint with a date range but without it took several minutes (sometimes more than 10...) to appear.
> 
> I didn't have two clients to check if this feature works as intended but it should work in theory if the API provides the correct info.
> 
> Also keep in mind that playback progress is only synced from Trakt via the import task and is dropped if the local last watched date is newer than the paused date of the playback.

Made a video about this https://www.youtube.com/watch?v=OvOTkuPjoAM
