### ISSUE TITLE
Removed collections not synced to Trakt

### ISSUE THREAD

**Issue by lldsolitude** [jellyfin/jellyfin-plugin-trakt#34]
When a movie or TV episode is added to my Jellyfin library, the Trakt plugin marks it as collected in Trakt when syncing. However, when the media file is removed, the plugin won't mark it as uncollected in Trakt. I understand that some people may have more than one media libraries so this may not be a desired feature, but would it be possible to add an option that enables this?

**Comment by philosen** [comment]
Would love to see an option added for this as well.

**Comment by dkanada** [comment]
I'm not entirely sure we have a listener for removed media, @Bond-009 do you know?

**Comment by Bond-009** [comment]
https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Controller/Library/ILibraryManager.cs#L220

**Comment by KaiStarkk** [comment]
Would also love to see this implemented to help keep trakt collections manageable.

**Comment by Shadowghost** [comment]
This should work as expected, we are handling deletion events within the plugin.
