### ISSUE TITLE
Sync library to trakt.tv - Error

### ISSUE THREAD

**Issue by EVOTk** [jellyfin/jellyfin-plugin-trakt#46]
Hello,
In Jellyfin - nightly - 20200605 - 10.6.0 , Sync library to trakt.tv is constantly failing
The problem was not present in version 10.5.5.

Plugin: 9.0.0.0

Import playstates from Trakt.tv - Okay
Sync library to trakt.tv - Error

> [2020-06-06 00:29:06.579 +02:00] [INF] [59] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Import playstates from Trakt.tv"
> [2020-06-06 00:29:06.579 +02:00] [INF] [59] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task "SyncFromTraktTask"
> [2020-06-06 00:29:06.579 +02:00] [INF] [59] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Import playstates from Trakt.tv"
> [2020-06-06 00:29:06.579 +02:00] [ERR] [59] Trakt: Exception handled
> System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_DecompressionMethod(MediaBrowser.Common.Net.CompressionMethod)'.
>    at Trakt.Api.TraktApi.GetHttpRequestOptions()
>    at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
>    at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
>    at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
> [2020-06-06 00:29:06.579 +02:00] [ERR] [59] Trakt: Error syncing trakt data for user "Evoluzione"
> System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_DecompressionMethod(MediaBrowser.Common.Net.CompressionMethod)'.
>    at Trakt.Api.TraktApi.GetHttpRequestOptions()
>    at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
>    at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
>    at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
>    at Trakt.ScheduledTasks.SyncFromTraktTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
> [2020-06-06 00:29:06.580 +02:00] [INF] [59] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Import playstates from Trakt.tv" Completed after 0 minute(s) and 0 seconds
> [2020-06-06 00:29:06.580 +02:00] [INF] [59] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
> [2020-06-06 00:29:06.610 +02:00] [INF] [38] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Sync library to trakt.tv"
> [2020-06-06 00:29:06.610 +02:00] [INF] [38] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task "SyncLibraryTask"
> [2020-06-06 00:29:06.610 +02:00] [INF] [38] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Sync library to trakt.tv"
> [2020-06-06 00:29:06.610 +02:00] [ERR] [38] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
> System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_DecompressionMethod(MediaBrowser.Common.Net.CompressionMethod)'.
>    at Trakt.Api.TraktApi.GetHttpRequestOptions()
>    at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
>    at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
>    at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
>    at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
>    at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
>    at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
> [2020-06-06 00:29:06.611 +02:00] [INF] [38] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Sync library to trakt.tv" Failed after 0 minute(s) and 0 seconds
> [2020-06-06 00:29:06.627 +02:00] [INF] [38] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks

**Comment by crobibero** [comment]
Plugins aren’t currently built to work with nightly, we will be updating all of the plugins once we are closer to a 10.6 release.

**Comment by EVOTk** [comment]
Thank you for your reply !
