### ISSUE TITLE
Conform to Branding Requirements

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-plugin-trakt#6]
Just as a heads up - Trakt has certain branding requirements when using their API. We should make sure that we comply with these when the plugin is installed.

Here they are for reference:
https://trakt.tv/branding

**Comment by anthonylavado** [comment]
If we can have a cover image for the plugin somewhere, I'd love to put their logo in.

**Comment by crobibero** [comment]
I'm considering this complete as we use their logo in the plugin image
