### ISSUE TITLE
Trakt plugin 11.0.0.0 + Jellyfin 10.7 not giving authroization code for user

### ISSUE THREAD

**Issue by Jinxyface** [jellyfin/jellyfin-plugin-trakt#60]
Just updated to  10.7 on Windows, which updated Trakt to 11.0.0.0, Was troubleshooting a trakt issue and wanted to re-authorize my user, however when I hit re-authroize, it isn't generating a code.

It just says "Please visit https://trakt.tv/activate and authorize Jellyfin to access your account.
Your device code is ." and where the code should be is blank.

Not sure what, if any, log files might be useful here. Please advise.

**Comment by oddstr13** [comment]
Seeing as you closed the issue, may I assume that it was intermittent, and solved itself?

**Comment by Jinxyface** [comment]
It seemed tied to that specific user. I made a new user and it worked as intended. So I assume it was just a user bug, nothing serious.  New user + quick trakt sync put me back where I was like nothing even happened.

**Comment by pgjensen** [comment]
Any ideas how to fix this without deleting my user?  I'm experiencing this as well.

**Comment by pgjensen** [comment]
I was able to fix this by doing:

sudo systemctl stop jellyfin.service
cd /path/to/data/for/jellyfin
sudo -u jellyfin vi plugins/configurations/Trakt.xml
#delete the TraktUser where the guid does NOT have hyphens in it
#you should be left with a single TraktUser (at least in my case) where the guid has hyphens (like <LinkedMbUserId>blahblah-blah-blah-blah-blahblah</LinkedMbUserId>)
sudo systemctl start jellyfin.service
