### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by pb1051** [jellyfin/jellyfin-plugin-trakt#7]
Is there a guide to follow to implement this plugin for a jellyfin container install?

**Comment by anthonylavado** [comment]
Hi @pb1051, just saw this while doing a review of all our open issues. This is now available for download through the plug-in page on 10.2 and newer. Hope this helps!

**Comment by pb1051** [comment]
For others: https://jellyfin.readthedocs.io/en/latest/

**Comment by anthonylavado** [comment]
Also for others: Yes, you can install it manually with the method in our documentation, but inside the Server Dashboard, you can use the Plug-in catalog to download it :smile:

**Comment by pb1051** [comment]
Sorry! Didn't know that was possible yet!
