### ISSUE TITLE
Scrobble progress is incorrect when resuming a show/movie

### ISSUE THREAD

**Issue by foux** [jellyfin/jellyfin-plugin-trakt#74]
When resuming a show/movie (ie, not starting from the beginning), the scrobble value will be incorrect, end offested by the time at which we started (for example, starting a movie at 60 minutes, when reaching 65 minutes the scrobble value will be 5 minutes on plex).

This is problematic when using the scrobble position to sync between players.

**Comment by Shadowghost** [comment]
Should be resolved with #112
