### ISSUE TITLE
traktresponse not found error

### ISSUE THREAD

**Issue by elvis0288** [jellyfin/jellyfin-plugin-trakt#75]
i am getting this when trying to sync to trakt, there is 2 tv shows that needs to sync as watched but it is not working
![image](https://user-images.githubusercontent.com/7027367/117151115-ab9d6380-adb0-11eb-9d70-afdbdd615b78.png)

**Comment by miracle152005** [comment]
I have the same problem.
After adding additional log entires and rebuilding the dll the reason at least on my end is that using Tvdb as the Identifier to add elements to the Trakt Collection is not good. Trakt switched to Tmdb as Source and Tvdb Ids can be missing or outdated for episodes.
Same for Imdb Ids.

**Comment by miracle152005** [comment]
Blog entry of the switch was released here:
https://blog.trakt.tv/tmdb-transition-ef3d19a5cf24

**Comment by Shadowghost** [comment]
Should be resolved by #93
