### ISSUE TITLE
Trakt is replacing TvDb with Tmdb and begins starting to delete tvdb ids on episodes

### ISSUE THREAD

**Issue by miracle152005** [jellyfin/jellyfin-plugin-trakt#80]
Hi,

trakt is moving from Tvdb to Tmdb and has begun to remove tvdb ids from episodes where information are matching between tmdb and tvdb.
This results in the trakt plugin no longer being able to sync episodes to the collection since the episodes with the tvdb id cannot be found.

Could you please take a look into it.

Best regards
miracle152005

**Comment by Shadowghost** [comment]
Should have been fixed by #93
