### ISSUE TITLE
Trakt plugin don't sync with trakt DB

### ISSUE THREAD

**Issue by moarf56** [jellyfin/jellyfin-plugin-trakt#83]
Hi, I use Jellyfin Version : 10.7.5 with trakt plugin V12.0.0.0. I decide to re install my jellyfin with the pluginn on onother machine.
Now the state of the show in my collection on jellyfin don't synchronise with trakt. When I watch an episode on jellyfin, jellyfin tell it to trakt BUT  trakt don't tell what I already watched to jeelyfin.

Any idees ?

THX

**Comment by Shadowghost** [comment]
Did you enable the required options for the user?

Also keep in mind that currently only watched state is imported, not playback progress.
