### ISSUE TITLE
Can't view settings page for Trakt on v12

### ISSUE THREAD

**Issue by theg00s3** [jellyfin/jellyfin-plugin-trakt#89]
So I'm not sure if this is an issue with 10.7.7 or the plugin's version 12 (but I suspect it's an issue with the plugin).

When I try to enter the settings page for the plugin, the settings are overlaid like this:
<img width="1787" alt="Screen Shot 2021-09-16 at 4 06 08 pm" src="https://user-images.githubusercontent.com/18522748/133558545-b62dee38-ebf4-4e55-b884-f72acd9db790.png">

I can refresh the page to get to the actual settings page, but none of the users appear in the dropdown.

I've also noticed that the plugin hasn't been scrobbling my watches either. However, if I downgrade to v11 I can interact with the settings pane.

**Comment by theg00s3** [comment]
On further investigation, the settings pane issue happens with a number of plugins, so it may be an issue with 10.7.7, but that doesn't explain why v11 works fine

**Comment by theg00s3** [comment]
So I have no idea what any of this means, but these are the errors that pop up with the browser's console open:

`Refused to load the script 'blob:https://media.berry2.top/24d39869-d5dd-43b1-ba0a-6838448e943d' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://www.gstatic.com/cv/js/sender/v1/cast_sender.js". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
main.0f18378….bundle.js:2`

`Uncaught (in promise) Error: Failed to import: https://media.berry2.top/web/configurationpage?name=traktjs at HTMLScriptElement.o.onerror`

It seems to be something to do with the reverse proxy, but those settings haven't changed in months

**Comment by crobibero** [comment]
sounds like you need to update your csp setting in the reverse proxy. 

If you’re using nginx you can find the latest version here: https://jellyfin.org/docs/general/networking/nginx.html

**Comment by theg00s3** [comment]
yep that was it. Thanks!
