### ISSUE TITLE
Certain Series don't sync

### ISSUE THREAD

**Issue by theg00s3** [jellyfin/jellyfin-plugin-trakt#90]
For some series, I just can't get Jellyfin/the Trakt plugin to scrobble plays of the show.
For example, with Dynasty (2017), this is the error that the Trakt plugin brings up (in debug mode):
`[2021-09-17 01:29:53.234 +10:00] [DBG] TraktSyncWatched { movies: null, shows: [], episodes: [TraktEpisodeWatched { watched_at: "2021-09-16T15:29:25Z", season: null, number: null, title: null, ids: TraktEpisodeId { imdb: null, tmdb: null, tvdb: 8429759, tvrage: null, trakt: null, slug: null } }] }` 

I'm not 100% sure what this shows, but the tvdb id definitely corresponds with the correct episode, and Trakt/TMDB have the correct episode ID listed. Jellyfin has the correct ID for IMDb, The TVDB and TVMaze. I'm very lost at trying to get this to work.

The same issue appears when trying to reflect collected series to Trakt as well. 

as a side note, I found this issue before, but I instead tried to reinstall the plugin, which ran me into #89

**Comment by crobibero** [comment]
The line you copied isn’t an error, it’s just stating exactly what the plugin is sending to Trakt. If the ID matches exactly I would say it’s an issue on their end.

**Comment by theg00s3** [comment]
ah ok, time to wrangle with Trakt support

**Comment by kevinkdev** [comment]
@theg00s3 did trakt say something about this issue. I am having the exact same issue. Movies are synced but TV Show play states no
